services:
  - type: web
    name: devert-backend
    runtime: docker
    region: singapore
    plan: free
    rootDir: devert-backend
    envVars:
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: PORT
        value: 8080
      - key: JUDGE0_API_KEY
        sync: false
      - key: JUDGE0_API_URL
        value: https://judge0-ce.p.rapidapi.com
      - key: JUDGE0_API_HOST
        value: judge0-ce.p.rapidapi.com
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
