// Seed DSA theory MCQs - the classic ground placement papers are set from.

export const dsaQuestions = [
  {
    id: "seed-dsa-001",
    type: "mcq",
    category: "dsa",
    topic: "complexity",
    difficulty: "easy",
    prompt: "What is the worst-case time complexity of binary search on a sorted array of n elements?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctIndex: 1,
    explanation:
      "Binary search halves the search space with every comparison, so at most ⌈log₂ n⌉ + 1 comparisons are needed - O(log n). It requires two things: the data must be sorted, and random access must be O(1) (arrays yes, linked lists no).",
    tags: ["binary-search", "complexity"],
  },
  {
    id: "seed-dsa-002",
    type: "mcq",
    category: "dsa",
    topic: "arrays",
    difficulty: "easy",
    prompt: "What is the time complexity of accessing the element at index i in an array of n elements?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
    correctIndex: 0,
    explanation:
      "Arrays are stored contiguously, so the address of index i is computed as base + i × elementSize - one arithmetic step regardless of n. That constant-time random access is the array's superpower, and exactly what linked lists give up in exchange for cheap insertion.",
    tags: ["arrays", "memory-layout"],
  },
  {
    id: "seed-dsa-003",
    type: "mcq",
    category: "dsa",
    topic: "linked-lists",
    difficulty: "medium",
    prompt:
      "Given only the head pointer, what is the time complexity of inserting a new node at the beginning of a singly linked list?",
    options: ["O(n)", "O(1)", "O(log n)", "O(n²)"],
    correctIndex: 1,
    explanation:
      "Front insertion is three constant-time steps: create the node, point it at the current head, and update the head pointer - O(1). Contrast this with inserting at the tail (O(n) without a tail pointer, since you must walk the whole list) and with array front-insertion (O(n) because every element shifts).",
    tags: ["linked-lists", "insertion"],
  },
  {
    id: "seed-dsa-004",
    type: "mcq",
    category: "dsa",
    topic: "stacks",
    difficulty: "easy",
    prompt: "Which data structure does a programming language runtime use to manage function calls and recursion?",
    options: ["Queue", "Stack", "Heap", "Graph"],
    correctIndex: 1,
    explanation:
      "Function calls follow last-in-first-out order - the most recently called function must return first - which is exactly a stack. The runtime pushes an activation record on every call and pops it on return; this is also why runaway recursion causes a \"stack overflow\" error.",
    tags: ["stacks", "recursion"],
  },
  {
    id: "seed-dsa-005",
    type: "mcq",
    category: "dsa",
    topic: "sorting",
    difficulty: "medium",
    prompt: "Which of the following sorting algorithms has the best WORST-CASE time complexity?",
    options: ["Quick sort", "Bubble sort", "Merge sort", "Insertion sort"],
    correctIndex: 2,
    explanation:
      "Merge sort guarantees O(n log n) even in the worst case, because it always splits the array exactly in half and merges in linear time. Quick sort degrades to O(n²) on adversarial pivot choices, and bubble/insertion sort are O(n²) - though insertion sort is O(n) on nearly-sorted data, a favourite follow-up question.",
    tags: ["sorting", "merge-sort", "complexity"],
  },
  {
    id: "seed-dsa-006",
    type: "mcq",
    category: "dsa",
    topic: "sorting",
    difficulty: "medium",
    prompt: "Which of the following sorting algorithms is STABLE?",
    options: ["Quick sort", "Heap sort", "Selection sort", "Merge sort"],
    correctIndex: 3,
    explanation:
      "A stable sort preserves the original relative order of equal elements. Merge sort is stable because on ties the merge step always takes from the left half first. Quick, heap and selection sort all jump elements across long distances and destroy the order of equals - stability matters when sorting by one key after another (e.g. by marks, then by name).",
    tags: ["sorting", "stability"],
  },
  {
    id: "seed-dsa-007",
    type: "mcq",
    category: "dsa",
    topic: "trees",
    difficulty: "medium",
    prompt: "What is the maximum number of nodes in a binary tree of height h (taking the root to be at height 0)?",
    options: ["2^h", "2^h − 1", "2^(h+1) − 1", "2h + 1"],
    correctIndex: 2,
    explanation:
      "A full binary tree has 2^L nodes at level L. Summing levels 0 through h: 2⁰ + 2¹ + … + 2^h = 2^(h+1) − 1. Watch the convention - if the question counts the root as height 1, the answer becomes 2^h − 1, so always check which convention the paper uses.",
    tags: ["trees", "counting"],
  },
  {
    id: "seed-dsa-008",
    type: "mcq",
    category: "dsa",
    topic: "binary-search-trees",
    difficulty: "medium",
    prompt: "The inorder traversal of a binary search tree always visits the keys in which order?",
    options: ["Ascending sorted order", "Descending sorted order", "Level order", "Random order"],
    correctIndex: 0,
    explanation:
      "Inorder traversal visits left subtree → node → right subtree. In a BST every key in the left subtree is smaller and every key in the right subtree is larger, so this order emits the keys in ascending sorted order. This property is also the standard O(n) way to verify that a tree really is a BST.",
    tags: ["bst", "traversals"],
  },
  {
    id: "seed-dsa-009",
    type: "mcq",
    category: "dsa",
    topic: "tree-traversals",
    difficulty: "hard",
    prompt:
      "The preorder traversal of a binary tree is A B D E C F and its inorder traversal is D B E A F C. What is the preorder traversal of the root's RIGHT subtree?",
    options: ["C F", "F C", "B D E", "E C F"],
    correctIndex: 0,
    explanation:
      "The first preorder element, A, is the root. In the inorder sequence D B E | A | F C, everything after A - {F, C} - forms the right subtree. Removing the left-subtree nodes from the preorder leaves C F: C is the right child of A, with F as C's left child (F precedes C in inorder). Splitting inorder around the root is the key move in every such question.",
    tags: ["traversals", "tree-construction"],
  },
  {
    id: "seed-dsa-010",
    type: "mcq",
    category: "dsa",
    topic: "hashing",
    difficulty: "medium",
    prompt: "What is the AVERAGE-case time complexity of searching for a key in a well-designed hash table?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctIndex: 0,
    explanation:
      "A good hash function spreads keys uniformly across buckets, so each bucket holds O(1) items on average and lookup is constant time. The worst case - all keys colliding into one bucket - degrades to O(n), which is why interviewers love asking for both cases together.",
    tags: ["hashing", "hash-tables"],
  },
  {
    id: "seed-dsa-011",
    type: "mcq",
    category: "dsa",
    topic: "graphs",
    difficulty: "medium",
    prompt: "Which graph traversal algorithm uses a QUEUE as its core data structure?",
    options: ["Depth First Search", "Breadth First Search", "Preorder traversal", "Topological sort using DFS"],
    correctIndex: 1,
    explanation:
      "BFS explores a graph level by level, which needs first-in-first-out order: visit a node, enqueue its unvisited neighbours, then dequeue the next node. DFS uses a stack (explicitly, or implicitly via recursion). A bonus fact worth remembering: BFS also finds shortest paths in unweighted graphs.",
    tags: ["graphs", "bfs"],
  },
  {
    id: "seed-dsa-012",
    type: "mcq",
    category: "dsa",
    topic: "heaps",
    difficulty: "medium",
    prompt: "In a binary min-heap containing n elements, what is the time complexity of extracting the minimum element?",
    options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctIndex: 1,
    explanation:
      "Extract-min removes the root, moves the last element to the top, then sifts it down - at most one swap per level, and a complete binary tree has ⌈log₂ n⌉ levels, so O(log n). Merely peeking at the minimum is O(1); it's the removal and re-heapify that costs log n.",
    tags: ["heaps", "priority-queues"],
  },
  {
    id: "seed-dsa-013",
    type: "mcq",
    category: "dsa",
    topic: "complexity",
    difficulty: "hard",
    prompt: "The recurrence T(n) = 2T(n/2) + n solves to which of the following?",
    options: ["O(n)", "O(n log n)", "O(n²)", "O(log n)"],
    correctIndex: 1,
    explanation:
      "By the Master Theorem with a = 2, b = 2 and f(n) = n: n^(log₂ 2) = n, which matches f(n), so T(n) = O(n log n) (case 2). Intuitively there are log n levels of recursion and each level does O(n) total work. This is exactly merge sort's recurrence - two half-size subproblems plus a linear merge.",
    tags: ["recurrences", "master-theorem"],
  },
  {
    id: "seed-dsa-014",
    type: "mcq",
    category: "dsa",
    topic: "stacks",
    difficulty: "medium",
    prompt: "What is the value of the postfix expression: 5 3 + 8 2 − *",
    options: ["46", "24", "48", "28"],
    correctIndex: 2,
    explanation:
      "Evaluate with a stack, left to right: 5 3 + → 8; then 8 2 − → 6; finally * pops 6 and 8 to give 8 × 6 = 48. Careful with − and ÷: the SECOND value popped is the left operand - computing 2 − 8 instead of 8 − 2 is the classic slip.",
    tags: ["postfix", "expression-evaluation"],
  },
];
