export const TEST = {
  subjectId: "algorithms",
  title: "Algorithms - Subject Test",
  description: "8 questions covering complexity analysis, searching, sorting, hashing, design techniques, and graph algorithms.",
  testType: "subject",
  durationMinutes: 45,
  instructions: "Standard GATE marking applies: MCQ negative marking (-1/3 for 1-mark, -2/3 for 2-mark), no negative marking for MSQ or NAT.",
  questions: [
    {
      questionType: "mcq", marks: 1, difficulty: "Easy",
      question: "An algorithm's running time is stated as O(n^2). Can it also correctly be described as O(n^3)?",
      options: [
        { id: "a", text: "No, O(n^2) rules out O(n^3)" },
        { id: "b", text: "Yes, a valid upper bound is still valid when loosened further" },
        { id: "c", text: "Only if n is very large" },
        { id: "d", text: "Cannot be determined" },
      ],
      correctOptionIds: ["b"],
      solution: "Big-O is an upper bound, not necessarily tight. If f(n)=O(n^2), then f(n)=O(n^3) is also technically true (a looser, still-valid bound).",
      explanation: "Only Big-Theta claims tightness; Big-O alone never rules out an even looser (but still correct) bound.",
    },
    {
      questionType: "nat", marks: 2, difficulty: "Moderate",
      question: "Solve the recurrence T(n) = 4T(n/2) + n using the Master Theorem. If T(n) = Theta(n^k), what is k?",
      natMin: 2, natMax: 2,
      solution: "a=4, b=2: n^(log_b a) = n^(log_2 4) = n^2. Compare f(n)=n against n^2: n grows slower (Case 1). T(n) = Theta(n^2), so k=2.",
      explanation: "Case 1 applies whenever f(n) grows strictly slower than n^(log_b a) - the recursive splitting dominates the combine work here.",
    },
    {
      questionType: "mcq", marks: 1, difficulty: "Moderate",
      question: "Which sorting algorithm is guaranteed O(n log n) in ALL cases AND uses only O(1) auxiliary space?",
      options: [
        { id: "a", text: "Quick sort" },
        { id: "b", text: "Merge sort" },
        { id: "c", text: "Heap sort" },
        { id: "d", text: "Insertion sort" },
      ],
      correctOptionIds: ["c"],
      solution: "Heap sort is O(n log n) in every case (unlike quick sort's O(n^2) worst case) and is in-place, O(1) auxiliary space (unlike merge sort's O(n) auxiliary array).",
      explanation: "This exact combination (guaranteed n log n AND in-place) is unique to heap sort among the standard comparison sorts.",
    },
    {
      questionType: "mcq", marks: 2, difficulty: "Hard",
      question: "Quick sort is run on an ALREADY-SORTED array using the 'always pick the last element as pivot' strategy. What is the resulting time complexity?",
      options: [
        { id: "a", text: "O(n log n) - quick sort is always this fast on average" },
        { id: "b", text: "O(n^2) - this specific input/pivot combination triggers the worst case" },
        { id: "c", text: "O(n) - sorted input is the best case" },
        { id: "d", text: "O(log n)" },
      ],
      correctOptionIds: ["b"],
      solution: "Picking the last element as pivot on already-sorted data creates maximally unbalanced partitions every time (one side empty) - exactly quick sort's O(n^2) worst case.",
      explanation: "A classic trap: 'sorted' sounds like it should be an easy case, but it's specifically the adversarial input for this particular pivot strategy.",
    },
    {
      questionType: "mcq", marks: 1, difficulty: "Moderate",
      question: "In a hash table using OPEN ADDRESSING, what happens if the load factor reaches exactly 1?",
      options: [
        { id: "a", text: "Performance improves" },
        { id: "b", text: "Further insertion fails - no empty slot exists to probe into" },
        { id: "c", text: "The table automatically switches to chaining" },
        { id: "d", text: "Nothing changes" },
      ],
      correctOptionIds: ["b"],
      solution: "Open addressing requires an empty slot for insertion. At load factor 1 (table completely full), no slot is available for any probe sequence to find.",
      explanation: "This is exactly why open addressing tables must be resized well before reaching load factor 1, unlike chaining which degrades more gracefully.",
    },
    {
      questionType: "mcq", marks: 1, difficulty: "Moderate",
      question: "Which classic problem does GREEDY correctly solve, in contrast to a similarly-named problem it does NOT solve correctly?",
      options: [
        { id: "a", text: "0/1 Knapsack (greedy works)" },
        { id: "b", text: "Fractional Knapsack (greedy works; 0/1 Knapsack needs DP instead)" },
        { id: "c", text: "Neither knapsack variant is solvable by greedy" },
        { id: "d", text: "Both knapsack variants are solved identically by greedy" },
      ],
      correctOptionIds: ["b"],
      solution: "Fractional Knapsack (items can be split) has the greedy-choice property - sort by value/weight ratio and greedily fill. 0/1 Knapsack (all-or-nothing) lacks this property and needs Dynamic Programming.",
      explanation: "This exact pairing is the single most commonly tested greedy-vs-DP distinction on GATE.",
    },
    {
      questionType: "nat", marks: 2, difficulty: "Moderate",
      question: "A connected graph has 9 vertices. How many edges does its Minimum Spanning Tree contain?",
      natMin: 8, natMax: 8,
      solution: "Any spanning tree on V vertices has exactly V-1 edges, by definition. V=9, so MST has 8 edges.",
      explanation: "This holds regardless of the graph's total edge count or specific weights - it's a structural fact about spanning trees.",
    },
    {
      questionType: "msq", marks: 2, difficulty: "Hard",
      question: "Which of the following statements about shortest-path algorithms are TRUE?",
      options: [
        { id: "a", text: "Dijkstra's algorithm requires all edge weights to be non-negative" },
        { id: "b", text: "Bellman-Ford can correctly handle negative edge weights (with no negative cycle)" },
        { id: "c", text: "Running Dijkstra's on a graph with a negative edge always produces an error message" },
        { id: "d", text: "Floyd-Warshall computes shortest paths between ALL pairs of vertices in one run" },
      ],
      correctOptionIds: ["a", "b", "d"],
      solution: "Dijkstra's requires non-negative weights (a: TRUE). Bellman-Ford handles negative weights correctly, absent a negative cycle (b: TRUE). Floyd-Warshall is specifically the all-pairs algorithm (d: TRUE). Dijkstra's on a negative-weight graph does NOT error - it silently produces a WRONG answer (c: FALSE), which is exactly why the precondition matters so much.",
      explanation: "Option (c) is the classic trap - Dijkstra's failure mode with negative weights is silent incorrectness, never a visible error.",
    },
  ],
};
