export const TEST = {
  subjectId: "compiler-design",
  title: "Compiler Design — Subject Test",
  description: "8 questions covering lexical analysis, parsing, syntax-directed translation, intermediate code, and optimization.",
  testType: "subject",
  durationMinutes: 45,
  instructions: "Standard GATE marking applies: MCQ negative marking (-1/3 for 1-mark, -2/3 for 2-mark), no negative marking for MSQ or NAT.",
  questions: [
    {
      questionType: "mcq", marks: 1, difficulty: "Easy",
      question: "In lexical analysis, what does the LONGEST MATCH rule specify?",
      options: [
        { id: "a", text: "The scanner should stop at the first valid match" },
        { id: "b", text: "When multiple matches are possible, the scanner picks the longest one" },
        { id: "c", text: "Tokens must always be exactly one character" },
        { id: "d", text: "The scanner ignores whitespace only" },
      ],
      correctOptionIds: ["b"],
      solution: "When more than one prefix of the remaining input could match a valid token, the scanner picks the LONGEST valid match - this is why '==' scans as one EQUALS token, not two '=' tokens.",
      explanation: "Without this rule, tokenization would be ambiguous whenever a shorter valid token is a prefix of a longer one.",
    },
    {
      questionType: "mcq", marks: 2, difficulty: "Moderate",
      question: "Which parsing technique specifically CANNOT handle a left-recursive grammar directly?",
      options: [
        { id: "a", text: "Bottom-up (LR) parsing" },
        { id: "b", text: "Top-down (LL) parsing / recursive descent" },
        { id: "c", text: "Both handle left recursion equally well" },
        { id: "d", text: "Neither can ever handle left recursion" },
      ],
      correctOptionIds: ["b"],
      solution: "Top-down parsing expanding a left-recursive nonterminal re-derives the SAME nonterminal immediately, looping forever without consuming input - left recursion must be eliminated first for top-down/LL parsing.",
      explanation: "Bottom-up (LR) parsers are not affected the same way, since they build from the leaves up rather than repeatedly expanding from the top.",
    },
    {
      questionType: "nat", marks: 1, difficulty: "Moderate",
      question: "How many three-address-code instructions (including the final assignment) are needed for x = (a + b) * (c - d)?",
      natMin: 3, natMax: 3,
      solution: "t1 = a + b; t2 = c - d; x = t1 * t2. Three instructions, one per operator (2 operators inside, plus the final assignment).",
      explanation: "Each TAC instruction can have at most ONE operator - counting the operators in the original expression (respecting parenthesization) directly gives the instruction count.",
    },
    {
      questionType: "mcq", marks: 1, difficulty: "Moderate",
      question: "An attribute computed from a node's own CHILDREN's values is called:",
      options: [
        { id: "a", text: "Inherited" },
        { id: "b", text: "Synthesized" },
        { id: "c", text: "Static" },
        { id: "d", text: "Global" },
      ],
      correctOptionIds: ["b"],
      solution: "A synthesized attribute is computed from a node's own children, flowing UPWARD from leaves toward the root.",
      explanation: "An inherited attribute instead comes from the parent or left siblings, flowing downward/sideways - the opposite direction.",
    },
    {
      questionType: "mcq", marks: 2, difficulty: "Hard",
      question: "What is the key structural advantage of a B+ tree's leaf-only data storage over a plain B-tree (which stores data at internal nodes too)?",
      options: [
        { id: "a", text: "B+ trees use less total memory always" },
        { id: "b", text: "Internal nodes can pack in more keys (higher fan-out), keeping the tree shallower, and leaves can be linked for fast range scans" },
        { id: "c", text: "B+ trees don't need to stay balanced" },
        { id: "d", text: "There is no real advantage" },
      ],
      correctOptionIds: ["b"],
      solution: "Since B+ tree internal nodes carry ONLY navigation keys (no data pointers), they fit more keys per node, increasing fan-out and reducing tree height/disk reads - and leaf-linking enables fast sequential range scans.",
      explanation: "This is exactly why B+ trees (not plain B-trees) are the standard database index structure - not a compiler-design topic per se, but this question tests recognizing the SAME underlying tree-height/fan-out reasoning that applies broadly.",
    },
    {
      questionType: "mcq", marks: 1, difficulty: "Moderate",
      question: "What is a BASIC BLOCK in compiler optimization?",
      options: [
        { id: "a", text: "Any single line of code" },
        { id: "b", text: "A maximal instruction sequence with one entry point and one exit point, no internal branches" },
        { id: "c", text: "The entire compiled program" },
        { id: "d", text: "A single function definition" },
      ],
      correctOptionIds: ["b"],
      solution: "A basic block has exactly one entry (first instruction) and one exit (last instruction), with no jumps into its middle or out except at the end - guaranteeing a fixed internal execution order.",
      explanation: "This fixed, predictable execution order is exactly what makes LOCAL optimizations (like peephole optimization) safe to apply within one basic block.",
    },
    {
      questionType: "nat", marks: 2, difficulty: "Hard",
      question: "In the code `x = 3; if (cond) x = x + 2; print(x);`, how many DISTINCT values can x provably hold at the print statement (per constant propagation analysis)?",
      natMin: 2, natMax: 2,
      solution: "Two paths reach print(x): the if-branch executed (x=5) or it didn't (x=3). Since these disagree, x is NOT a single known constant - exactly 2 distinct possible values exist at that point.",
      explanation: "This is exactly why constant propagation must check that EVERY incoming path agrees before treating a variable as a known constant at a merge point.",
    },
    {
      questionType: "msq", marks: 2, difficulty: "Hard",
      question: "Which of the following statements about data-flow analyses are TRUE?",
      options: [
        { id: "a", text: "Liveness analysis is a BACKWARD data-flow analysis" },
        { id: "b", text: "Available expressions analysis is a FORWARD data-flow analysis" },
        { id: "c", text: "Constant propagation only needs to examine one instruction at a time, never the full control flow graph" },
        { id: "d", text: "A basic block's use[B] set contains variables read before any redefinition within that block" },
      ],
      correctOptionIds: ["a", "b", "d"],
      solution: "Liveness is backward (depends on future use) (a: TRUE). Available expressions is forward (follows computation direction) (b: TRUE). use[B] is exactly variables read-before-redefined within B (d: TRUE). Constant propagation specifically requires examining the WHOLE control flow graph (merging multiple paths), not just one instruction (c: FALSE) - that's the whole reason it's a data-flow analysis, not local folding.",
      explanation: "Liveness (backward) and available expressions (forward) moving in OPPOSITE directions is a frequently tested distinction between the two data-flow analyses.",
    },
  ],
};
