export const TEST = {
  subjectId: "databases",
  title: "Databases - Subject Test",
  description: "8 questions covering ER modeling, relational algebra/SQL, normalization, indexing, and transactions.",
  testType: "subject",
  durationMinutes: 45,
  instructions: "Standard GATE marking applies: MCQ negative marking (-1/3 for 1-mark, -2/3 for 2-mark), no negative marking for MSQ or NAT.",
  questions: [
    {
      questionType: "mcq", marks: 1, difficulty: "Easy",
      question: "An M:N relationship between two entities is converted to relational tables. How is it best represented?",
      options: [
        { id: "a", text: "A foreign key added to either entity's table" },
        { id: "b", text: "A separate junction table with a composite key of both entities' keys" },
        { id: "c", text: "Merging both entities into one table" },
        { id: "d", text: "M:N relationships cannot be represented relationally" },
      ],
      correctOptionIds: ["b"],
      solution: "M:N relationships require a dedicated junction table, since each side can relate to multiple instances on the other - a single foreign key can never capture this.",
      explanation: "1:1 and 1:N relationships CAN use a simple foreign key; only M:N specifically requires the separate table with a composite key.",
    },
    {
      questionType: "mcq", marks: 2, difficulty: "Moderate",
      question: "In SQL, what is the LOGICAL execution order of clauses (not written order)?",
      options: [
        { id: "a", text: "SELECT, FROM, WHERE, GROUP BY, HAVING, ORDER BY" },
        { id: "b", text: "FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY" },
        { id: "c", text: "WHERE, FROM, SELECT, GROUP BY, HAVING, ORDER BY" },
        { id: "d", text: "FROM, SELECT, WHERE, GROUP BY, HAVING, ORDER BY" },
      ],
      correctOptionIds: ["b"],
      solution: "The logical order is FROM (build rows) -> WHERE (filter rows) -> GROUP BY (form groups) -> HAVING (filter groups) -> SELECT (compute output) -> ORDER BY (sort) - genuinely different from written order.",
      explanation: "This exact order explains why WHERE cannot use an aggregate function (HAVING exists specifically for that) and why WHERE cannot reference a SELECT alias.",
    },
    {
      questionType: "mcq", marks: 1, difficulty: "Moderate",
      question: "Why does `WHERE column = NULL` never match any rows, even ones where column actually IS NULL?",
      options: [
        { id: "a", text: "It's a syntax error" },
        { id: "b", text: "Any comparison involving NULL evaluates to UNKNOWN, never TRUE" },
        { id: "c", text: "NULL is treated as the string 'NULL'" },
        { id: "d", text: "WHERE cannot be used with NULL at all" },
      ],
      correctOptionIds: ["b"],
      solution: "SQL's three-valued logic makes any direct comparison with NULL evaluate to UNKNOWN, never TRUE - WHERE only includes rows where the condition is TRUE. IS NULL is the correct syntax.",
      explanation: "This trap is one of the most commonly tested SQL/NULL behaviours.",
    },
    {
      questionType: "nat", marks: 2, difficulty: "Moderate",
      question: "A relation R(A,B,C,D) has FDs A->B and B->C. Given A is the key, how many attributes does the closure of {A} (A+) contain?",
      natMin: 3, natMax: 3,
      solution: "A+ starts with {A}. A->B adds B: {A,B}. B->C adds C: {A,B,C}. No further FD applies (nothing determines D from this set) - the closure {A,B,C} has 3 attributes.",
      explanation: "D is left out because no given functional dependency lets us derive D from A - this shows R as given is NOT actually fully determined by A alone unless D is separately guaranteed by A (not stated here).",
    },
    {
      questionType: "mcq", marks: 2, difficulty: "Hard",
      question: "A relation R(A,B,C) has FDs A->B and B->C, with A as the only candidate key. Which normal form does R violate?",
      options: [
        { id: "a", text: "1NF" },
        { id: "b", text: "2NF" },
        { id: "c", text: "3NF (due to the transitive dependency A->B->C)" },
        { id: "d", text: "R is already in BCNF" },
      ],
      correctOptionIds: ["c"],
      solution: "C depends on A only THROUGH B (a transitive dependency of non-key attribute C on non-key attribute B) - this is exactly the anomaly 3NF forbids.",
      explanation: "2NF's partial dependency concern only applies to COMPOSITE keys - since A alone is the key here, 2NF isn't the violation; it's specifically the transitive dependency that breaks 3NF.",
    },
    {
      questionType: "mcq", marks: 1, difficulty: "Moderate",
      question: "What is the primary reason B+ trees (not plain binary search trees) are used for database indexes?",
      options: [
        { id: "a", text: "B+ trees use less code to implement" },
        { id: "b", text: "B+ trees have much higher fan-out, keeping the tree shallow and minimizing disk-block reads" },
        { id: "c", text: "B+ trees don't require sorted keys" },
        { id: "d", text: "There is no real advantage" },
      ],
      correctOptionIds: ["b"],
      solution: "A B+ tree's high fan-out per node keeps the tree height dramatically smaller than a binary tree for the same record count - since each level typically means one disk read, a shallower tree means far fewer expensive disk accesses.",
      explanation: "Disk-block-read minimization (not raw comparison count) is the actual bottleneck B+ trees are optimized for.",
    },
    {
      questionType: "mcq", marks: 2, difficulty: "Hard",
      question: "A precedence graph for a schedule has edges T1->T2, T2->T3, T3->T1. Is this schedule conflict serializable?",
      options: [
        { id: "a", text: "Yes, as long as all edges are shown" },
        { id: "b", text: "No - the graph contains a cycle" },
        { id: "c", text: "Cannot be determined from the graph alone" },
        { id: "d", text: "Yes, cycles don't affect serializability" },
      ],
      correctOptionIds: ["b"],
      solution: "Conflict serializability corresponds exactly to the precedence graph being ACYCLIC. T1->T2->T3->T1 is a cycle, so the schedule is NOT conflict serializable.",
      explanation: "This graph-based check is exact, not a heuristic - acyclic always means serializable, any cycle always means not serializable.",
    },
    {
      questionType: "msq", marks: 2, difficulty: "Hard",
      question: "Which of the following statements about ACID properties and concurrency control are TRUE?",
      options: [
        { id: "a", text: "Atomicity guarantees a transaction either fully completes or has no effect at all" },
        { id: "b", text: "Basic Two-Phase Locking (2PL) alone prevents cascading rollbacks" },
        { id: "c", text: "Strict 2PL holds all locks until commit/abort, which does prevent cascading rollbacks" },
        { id: "d", text: "Isolation guarantees concurrent transactions appear to execute as if run one at a time" },
      ],
      correctOptionIds: ["a", "c", "d"],
      solution: "Atomicity: all-or-nothing (a: TRUE). Isolation: concurrent transactions appear serial (d: TRUE). Strict 2PL specifically prevents cascading rollbacks by holding all locks until commit/abort (c: TRUE). Basic 2PL alone guarantees serializability but does NOT prevent cascading rollbacks (b: FALSE) - that specific guarantee requires the stronger Strict 2PL variant.",
      explanation: "The distinction between basic 2PL (serializable only) and Strict 2PL (also cascade-free) is a frequently tested, easy-to-miss nuance.",
    },
  ],
};
