export const TEST = {
  subjectId: "digital-logic",
  title: "Digital Logic - Subject Test",
  description: "8 questions covering Boolean algebra, minimization, combinational/sequential circuits, and number representation.",
  testType: "subject",
  durationMinutes: 45,
  instructions: "Standard GATE marking applies: MCQ negative marking (-1/3 for 1-mark, -2/3 for 2-mark), no negative marking for MSQ or NAT.",
  questions: [
    {
      questionType: "mcq", marks: 1, difficulty: "Easy",
      question: "Which gate(s) are individually 'universal' (can build any other gate alone)?",
      options: [
        { id: "a", text: "AND and OR only" },
        { id: "b", text: "NAND and NOR only" },
        { id: "c", text: "XOR and XNOR only" },
        { id: "d", text: "All gates are universal" },
      ],
      correctOptionIds: ["b"],
      solution: "NAND and NOR are each individually universal - any other gate can be built using only NAND (or only NOR).",
      explanation: "AND/OR/NOT are each individually monotonic and cannot build the others from just one type; XOR/XNOR cannot produce AND from repeated self-combination either.",
    },
    {
      questionType: "nat", marks: 1, difficulty: "Moderate",
      question: "How many rows does the truth table for a boolean function of 5 variables have?",
      natMin: 32, natMax: 32,
      solution: "A function of n variables has 2^n rows. For n=5: 2^5 = 32.",
      explanation: "This scales exponentially - doubling with each additional variable.",
    },
    {
      questionType: "mcq", marks: 2, difficulty: "Moderate",
      question: "Simplify the boolean expression F = A'BC + AB'C + ABC' + ABC.",
      options: [
        { id: "a", text: "AB + BC + AC" },
        { id: "b", text: "A + B + C" },
        { id: "c", text: "ABC" },
        { id: "d", text: "AB + BC" },
      ],
      correctOptionIds: ["a"],
      solution: "Grouping via K-map: this is the sum of minterms where at least 2 of A,B,C are 1. This simplifies to the majority function: AB + BC + AC.",
      explanation: "Recognising 'at least 2 of 3 inputs true' as the majority function pattern (AB+BC+AC) is a fast shortcut over full K-map grouping for this specific, common structure.",
    },
    {
      questionType: "mcq", marks: 1, difficulty: "Easy",
      question: "What is the 2's complement representation of -5 in 8 bits?",
      options: [
        { id: "a", text: "11111010" },
        { id: "b", text: "11111011" },
        { id: "c", text: "00000101" },
        { id: "d", text: "10000101" },
      ],
      correctOptionIds: ["b"],
      solution: "5 = 00000101. Invert all bits: 11111010. Add 1: 11111011.",
      explanation: "The two-step process (invert, then add 1) must both be applied - inverting alone (option a) gives the 1's complement, not the 2's complement.",
    },
    {
      questionType: "mcq", marks: 2, difficulty: "Moderate",
      question: "A JK flip-flop has J=1, K=1 on a clock edge. What is the next state Q(next)?",
      options: [
        { id: "a", text: "0" },
        { id: "b", text: "1" },
        { id: "c", text: "Toggles (complement of current Q)" },
        { id: "d", text: "Undefined/invalid" },
      ],
      correctOptionIds: ["c"],
      solution: "J=1, K=1 is the JK flip-flop's TOGGLE condition - Q(next) = Q'(current), the complement of whatever the current state was.",
      explanation: "This is exactly the case that SR flip-flops leave undefined (both set and reset asserted) - the JK flip-flop's extra logic specifically resolves this into a well-defined toggle instead.",
    },
    {
      questionType: "nat", marks: 2, difficulty: "Moderate",
      question: "How many flip-flops are needed to build a MOD-13 counter (counts 0 through 12)?",
      natMin: 4, natMax: 4,
      solution: "Need 2^n >= 13. 2^3=8 (too few), 2^4=16 (enough). So 4 flip-flops are needed (with reset/skip logic to stop at 13 states instead of the full 16).",
      explanation: "The number of flip-flops is determined by the smallest n where 2^n covers the needed state count, not by the modulus number directly.",
    },
    {
      questionType: "mcq", marks: 1, difficulty: "Moderate",
      question: "In IEEE 754 single precision (32-bit) floating point, how many bits are allocated to the exponent?",
      options: [
        { id: "a", text: "23" },
        { id: "b", text: "8" },
        { id: "c", text: "1" },
        { id: "d", text: "11" },
      ],
      correctOptionIds: ["b"],
      solution: "IEEE 754 single precision: 1 sign bit + 8 exponent bits + 23 mantissa bits = 32 bits total.",
      explanation: "11 exponent bits belongs to DOUBLE precision (64-bit), not single precision - a common mix-up between the two formats.",
    },
    {
      questionType: "msq", marks: 2, difficulty: "Hard",
      question: "Which of the following statements about the Quine-McCluskey tabular minimization method are TRUE?",
      options: [
        { id: "a", text: "It groups minterms by the number of 1s in their binary representation" },
        { id: "b", text: "It is only usable for functions with 4 or fewer variables" },
        { id: "c", text: "It can be mechanically automated, unlike a K-map" },
        { id: "d", text: "It identifies prime implicants systematically" },
      ],
      correctOptionIds: ["a", "c", "d"],
      solution: "Quine-McCluskey groups minterms by 1-count (a: TRUE), is systematic enough to automate in software unlike the visual K-map (c: TRUE), and its core purpose is finding all prime implicants (d: TRUE). It scales BEYOND K-map's practical 4-5 variable visual limit, specifically because it's tabular rather than visual (b: FALSE).",
      explanation: "The tabular method's main advantage over K-maps is exactly that it doesn't rely on visual grouping, so it scales to more variables and can be automated.",
    },
  ],
};
